### ISSUE TITLE
Error getting card data for 328000, please report this! Same with 33680.

### ISSUE THREAD

**Issue by Deadsy81** [Ryzhehvost/ASF-STM#12]
Got this today, Had not done a scan in 2-3 days, but the problems didn't occur earlier.

And now that I'm running a third run no errors occurred.

**Comment by Ryzhehvost** [comment]
Thank you for the report! I'm working on an ultimate fix for such errors, ETA: SOON™ (valve time)

**Comment by Ryzhehvost** [comment]
Should be resolved with #14
