### ISSUE TITLE
Error getting card data for 1484900, please report this!

### ISSUE THREAD

**Issue by AmanoTC** [Ryzhehvost/ASF-STM#13]
See title.
Script aborts due to error.

**Comment by Ryzhehvost** [comment]
Thank you for the report! New version that should fix those errors for good is almost ready, ETA: next few days (if nothing goes wrong).

**Comment by AmanoTC** [comment]
> Thank you for the report! New version that should fix those errors for good is almost ready, ETA: next few days (if nothing goes wrong).

New error: Error getting card data for 1498570, please report this!

Well, it's the same error, just a different card, I guess, so I'm not opening a new issue. Thank you for your work!

**Comment by Ryzhehvost** [comment]
Should be resolved with #14
