### ISSUE TITLE
Нет защиты от ошибки во время XML-запроса профиля

### ISSUE THREAD

**Issue by Wolterhon** [Ryzhehvost/ASF-STM#2]
Стопорился скрипт на боте, глянул консоль, а там
`Uncaught TypeError: Cannot read property '1' of null
    at XMLHttpRequest.xhr.onload`
а именно тут:
![chrome_w1FScjIuj4](https://user-images.githubusercontent.com/23475741/106592414-4a77b100-6571-11eb-9987-ad0c8977fc6f.png)
Проблема в том, что XML-запрос возвращал страницу "Извините! Невозможно загрузить данные профиля", а на это, как я понял, в скрипте проверки нет, поэтому он просто повисает. Исправьте, пожалуйста :)

**Comment by Ryzhehvost** [comment]
Чёртов стим, значит он возвращает ошибку с кодом 200. К такому жизнь меня не готовила.  Спасибо, как будет время - добавлю проверку.

**Comment by Ryzhehvost** [comment]
Closed with #3
