### ISSUE TITLE
addMatchRow not called on regex match error

### ISSUE THREAD

**Issue by iBreakEverything** [Ryzhehvost/ASF-STM#5]
https://github.com/Ryzhehvost/ASF-STM/blob/master/ASF-STM.user.js#L571

addMatchRow call should be outside of if body

**Comment by Ryzhehvost** [comment]
Just putting it outside of if body makes no sense. But now that I think of it - we can use steamID instead of username in case if we can't fetch it.

**Comment by Ryzhehvost** [comment]
Thank you for the report, fixed.
