### ISSUE TITLE
Error getting hashname for card Mystery Card 5

### ISSUE THREAD

**Issue by Wolterhon** [Ryzhehvost/ASF-STM#6]
![изображение](https://user-images.githubusercontent.com/23475741/208032945-f424157d-4d76-49af-86b5-ee2c7b6b6772.png)

**Comment by Ryzhehvost** [comment]
What version of script do you have? This issue should be fixed in 2.4 and above

**Comment by Wolterhon** [comment]
Yep, the friend who had this error had 2.3, so I guess that's the problem.
